### ISSUE TITLE
Dates mismatch between FRED and imported data

### ISSUE THREAD

**Issue by ceschi** [sboysel/fredr#1]
Hi! I have been using fredr for my research, but recently I have noticed that some imported series do not display correct start and end dates when compared with dates on Fred website. To give an example:

`df <- fredr_series(series_id='FGCCSAQ027S', frequency='q')`

is a series from 1945-10-01 to 2016-10-01 (or, in quarters, 1945Q4 - 2016Q4). Once it is imported, regardless of the specific format (I use both ts and xts), R shows that it starts in 1947Q2 and ends in 2018Q2.
This issue, nevertheless, is not present in all series. For instance, when I run the same code for another series
`df.xts <- as.xts(fredr_series(series_id='FDHBFRBN', frequency='q'))`

beginnings and ends match as usual. Any explanation for this behaviour?

**Comment by sboysel** [comment]
Hi @ceschi ,

Thanks for bringing this to my attention.  The inconsistency arose from poor handling of time series parsing in `fredr_series`.  Since  691ca81d95e2a2df74db5862b7a6326a312870f5, I've opted for simply returning the series values and dates a an `xts` object.  Can you update `fredr` and try again?

```{r}
devtools::install_github('sboysel/fredr')
fredr_series(series_id = 'FGCCSAQ027S')
```

**Comment by sboysel** [comment]
Correct. That is a conscious choice to return a simple object containing observation dates and values without loss of data fidelity.  If you want to coerce the returned object to a quarterly `ts` object:

```r
x <- fredr_series(series_id = 'FGCCSAQ027S')
ts(data = x, start = c(1945, 3), frequency = 4)
```

or convert the existing object to quarterly using `zoo::as.yearqtr`

```r
library(zoo)
index(x) <- as.yearqtr(index(x))
```

**Comment by ceschi** [comment]
Thank you! very clear and useful, I'll fix my code right away!
