### ISSUE TITLE
Option to select Seasonally Adjusted Observation

### ISSUE THREAD

**Issue by ericvmai** [sboysel/fredr#102]
Is there a variable in the fredr() function that allows you to choose the "Seasonally Adjusted" observation instead of the "Not Seasonally Adjusted"? I have to choose some different variables to get there but would prefer a variable that allows me to choose that.

**Comment by sboysel** [comment]
AFAIK, FRED series are seasonally adjusted at the series level and there is no option exposed by the endpoint [`fredr/series/observations`](https://fred.stlouisfed.org/docs/api/fred/series_observations.html) (i.e. the function `fredr::fredr`) to select different versions by this particular adjustment. A series and it's seasonally adjusted counterpart will have distinct series IDs.  What you can do is use the `filter_variable` parameter from one of the [`fredr::fredr_search_*`](https://sboysel.github.io/fredr/reference/fredr_series_search.html) functions to search for a seasonally adjusted version of a series.
