### ISSUE TITLE
Use time aware tables

### ISSUE THREAD

**Issue by sboysel** [sboysel/fredr#19]
For `fredr_series` returns.

See [business-science/tibbletime](https://github.com/business-science/tibbletime).  Would reintroduce to some heavier dependencies.

**Comment by DavisVaughan** [comment]
I think it's better to just stay with `tibble`. The dependencies are heavy enough that some people will complain, which I can understand. It's a nice thought though.

**Comment by sboysel** [comment]
Right. I'll close for now.
