### ISSUE TITLE
Implement functions for endpoint: Tags

### ISSUE THREAD

**Issue by sboysel** [sboysel/fredr#25]
https://research.stlouisfed.org/docs/api/fred/#Tags

The following endpoints need to be implemented properly and consistently in `fredr`:

- [x] `fredr_tags()` - Get all tags, search for tags, or get tags by name. (#28)
- [ ] `fredr_related_tags()` - Get the related tags for one or more tags.
- [ ] `fredr_tags_series()` - Get the series matching tags.

The functions are to be implemented with explicit arguments for each parameter in the FRED API (see [documentation](https://research.stlouisfed.org/docs/api/fred/#Series) for each endpoint and the discussion in #20).

**Comment by DavisVaughan** [comment]
I'll take this one

**Comment by DavisVaughan** [comment]
Important note. The JSON example uses `monetary+aggregates;weekly` as the example. `httr::GET` transforms the `+` into `%2B` which the FRED API apparently does not accept. An alternative is to just use a space, `monetary aggregates;weekly` where the space turns into `%20` which seems to be fine. I'm going to have a validation function that checks this.
