### ISSUE TITLE
Consistent unit tests

### ISSUE THREAD

**Issue by sboysel** [sboysel/fredr#26]
As of now, unit testing is quite haphazard.  I'd like to establish a consistent set of tests for each function.

1. `fredr_set_key()` - fine as is
2. `fredr()`
   - errors when API key is not set
   - errors for bad endpoint
   - errors for non-200 HTTP response
   - return should always be a tibble.
3. Endpoint functions wrapped around `fredr()` 
   - errors for bad parameter names and values**
   - return should always be a tibble.

Note that the FRED API will return

- a `404` error if the request URL is not found (e.g. bad endpoint passed to `fredr()`)
- a `400` if the endpoint is value but the request is improperly formed (e.g. bad parameters passed to `fredr()` or the endpoint functions).

Some initial testing suggests the FRED API `400` codes return useful error messages for bad values and that improperly named parameters are simply ignored (explicitly defined parameters would solve this anyways).

** @DavisVaughan What would you consider best practice for errors in an API package: check that parameter value types are proper *before* sending the request or allow the API to return an error?

**Comment by DavisVaughan** [comment]
We should also think about cases where 0 row tibbles are returned, because I think i ran into an issues with `fredr_series` where that failed with a strange (at least to a user) error.

**Comment by DavisVaughan** [comment]
Eventually for CRAN we will likely need a skip_if_no_auth() function. See riingo helper R file. Must be named helper_*.R for testthat. https://github.com/business-science/riingo/tree/master/tests/testthat

Also might get CRAN push back on donttest{} wrapped code, but I got around it by explaining my reasoning that auth is needed for testing and that I test extensively on Travis for riingo

**Comment by sboysel** [comment]
I see.  Any idea on how to deal with vignettes when the API key isn't present?

**Comment by DavisVaughan** [comment]
See the reply from `hrbrmstr` here https://stackoverflow.com/questions/47333912/r-package-vignette-include-api-key it covers all the bases of what you should do for API testing.

`rtweet` generally follows that advice and sets `eval = FALSE` for the chunks in the vignette. Its annoying but its the best you can do i think. I wouldnt try and cache / save data and try and load it in (to mock the API calls) unless it was really small files
http://rtweet.info/articles/intro.html
https://raw.githubusercontent.com/mkearney/rtweet/master/vignettes/intro.Rmd

**Comment by sboysel** [comment]
Thanks for the tip!  I'll follow that

**Comment by sboysel** [comment]
Tests were overhauled to adopt this framework in f20f51031c084b8d469d006375b6e4422b8a4550.  We can extend and modify testing as needed as development continues.  Some remarks:

- The use of helper functions defined in `R/validation.R` can be used to extend function checking
- `fredr()` endpoint validation (a6d82f815d2a009f2d86a4451ca1eef9e3413635)
- `skip_if_no_key()` defined and used in tests requiring authentication (#29 )
- Vignette chunks are cached and not evaluated when the API key is not present (72e5ddd7fcbd62578c360b5f435ecfcc6b789748)
