### ISSUE TITLE
tar.gz release archive

### ISSUE THREAD

**Issue by hedgehog** [sboysel/fredr#4]
Hi Given the problems installing reported in issue #3, I tried to install from an archive.  R requires tar.gz files.

Further when I tried to unpack the .zip archive to create the tar.gz myself winzip remports the zip file is corrupt.  I've tried several downloads.

Hope that helps.

**Comment by sboysel** [comment]
Hi @hedgehog,

I'm not sure exactly what steps you've followed.  What is the output when you try:

```r
download.file(
  url = "https://github.com/sboysel/fredr/archive/master.zip",
  destfile = "fredr-master.zip"
)
utils::unzip(zipfile = "fredr-master.zip", exdir = "fredr-master")
devtools::install(pkg = "fredr-master")
```

As in #3 , verify that Rtools is installed first.

Thanks for using the package!

Sam
