### ISSUE TITLE
Maybe alias `fredr_series_observations()`?

### ISSUE THREAD

**Issue by DavisVaughan** [sboysel/fredr#44]
We've talked about the fact that `fredr_series_observations()` is likely going to be the most popular function of the package, but is also annoying to type. What if, since it really is __the__ function in the package, we aliased it with `fredr()` (we would keep both and they could share a Rd file)?

We'd have to go back and replace the current `fredr()` function with something like `fredr_request()`, but that wouldn't be the end of the world.

Feel free to disagree! Just an idea

**Comment by sboysel** [comment]
Yes I think this is a good idea

- `fredr_request()` to form a general request
- `fredr_series_observations()` to fetch observations
- `fredr()` as an alias for `fredr_series_observations()`

Let's implement the documentation work.

**Comment by sboysel** [comment]
Closed with #46
