### ISSUE TITLE
Initial Version

### ISSUE THREAD

**Issue by sboysel** [sboysel/fredr#59]
Given the way we've change the API over the last few weeks, I think 1.0.0 is appropriate for the initial CRAN release.  Just wanted to get your thoughts, @DavisVaughan

**Comment by DavisVaughan** [comment]
Agreed! These are major breaking changes and I see no immediate reason that the API would have any further breaking changes after this, so 1.0.0 sounds appropriate with 1.1.0 being the next and so on

**Comment by sboysel** [comment]
Perfect.  I'll go ahead and do the following:

- Tag master with v1.0.0
- Update the changelog
- [Submit to CRAN](https://cran.r-project.org/submit.html).  Newbie question: CRAN comments should go in the Optional Comments text box at the submission portal?  Don't want to make any assumptions on what the maintainers will read.

**Comment by DavisVaughan** [comment]
I would use devtools::release() for submitting to CRAN. I've never used the portal itself, devtools does it for you. You will just have to click something in an email you get after using devtools verifying your submission. Assume they skim the cran comments file we added, it's a standard file they likely read. Don't be upset if we get a first round rejection. Make sure and do a devtools::check() as well. devtools::release also runs a much more intensive check I think

**Comment by DavisVaughan** [comment]
Are we waiting on a response from CRAN for this?

**Comment by sboysel** [comment]
Yes. The last update I got was that the package was pending manual inspection (4 days ago, the second resubmission).

**Comment by DavisVaughan** [comment]
I see it here in the inspect section of their lesser known ftp site ftp://cran.r-project.org/incoming/inspect/

Looks like more backlog there than I usually see

**Comment by sboysel** [comment]
Just got word that `fredr` is on its way to CRAN!

**Comment by DavisVaughan** [comment]
HYPE
https://cran.r-project.org/web/packages/fredr/index.html

**Comment by DavisVaughan** [comment]
I'm going to post on social media (with 100% credit to you) if that's cool?

**Comment by sboysel** [comment]
Yeah please spread the word. Thanks.  Credit isn't super important to me.  I really appreciate all the help.

**Comment by DavisVaughan** [comment]
Happy to be able to share some knowledge I've gained over the years. It's been a pleasure building this out with you!
