### ISSUE TITLE
limit of 1000 on fredr_search()

### ISSUE THREAD

**Issue by peterxeno** [sboysel/fredr#7]
Is it possible to pull more than 1000 records with `fredr_search()` ?

**Comment by sboysel** [comment]
No, this is an [API limit](https://research.stlouisfed.org/docs/api/fred/series_search.html#limit).  But you came mimic pagination using the parameter `offset`.  Documentation [here](https://research.stlouisfed.org/docs/api/fred/series_search.html#offset).
