### ISSUE TITLE
Encoding error with fredr_series_observations

### ISSUE THREAD

**Issue by ceschi** [sboysel/fredr#71]
Hi,
In recent days I have been experiencing a new error with fredr_series_observations while fetching data from FRED, as R throws the following error
```
No encoding supplied: defaulting to UTF-8.
Error in (function (endpoint, ..., to_frame = TRUE, print_req = FALSE)  : 
  : 
```
 Until last week all was working smoothly. What is a bit strange is that it appears to be totally unpredictable: if I call the fredr_series_observations function from a script with `source` or running the code line-by-line it makes little difference. Any hint?
Thanks!

**Comment by ceschi** [comment]
nothing?

**Comment by DavisVaughan** [comment]
Can you post a reproducible example of the code that triggers the error? Or the full error message?

Even if it happens randomly, that will give us something to call repeatedly on our end to try and trigger what you are seeing.

It is very hard to help without any examples.

**Comment by sboysel** [comment]
> No encoding supplied: defaulting to UTF-8.

I'm pretty that is an encoding *message*, not an error, from the `httr::content` call within `fredr::fredr_request`.  We can explicitly pass `utf8` to the `encoding` parameter of `httr::content`.

The actual error you are experiencing would be better diagnosed, as suggested by @DavisVaughan, with a reproducible example.

**Comment by ceschi** [comment]
I agree the encoding piece is a message not an error, the `Error in (function (endpoint, ..., to_frame = TRUE, print_req = FALSE)  :` part seems an error and it prevents the correct execution of the code. I am currently running again the script (both lin-by-line and as `source(script.R)` but the error is not popping up, while yesterday it did. I wonder if it is something related to release dates of some particular data series.

**Comment by DavisVaughan** [comment]
Could you please provide the lines of code that you are running?

**Comment by ceschi** [comment]
as soon as I can reproduce the error and find the exact line that triggers it I will post it, as of now it seems to work

**Comment by ceschi** [comment]
This seems to be the piece of code behind the error

`base <- fredr_series_observations(series_id='BOGMBASE', frequency='q') %>% tbl_xts() %>% `/`(.,1000)`

**Comment by sboysel** [comment]
@ceschi I cannot seem to reproduce that error with `fredr 1.0.0`.  Not sure I understand the `/(.,1000)` part, perhaps it was a typo.  It seems like you're using this line as part of a more complicated script or function.  If the issue persists, try to [use the debugger](https://support.rstudio.com/hc/en-us/articles/205612627-Debugging-with-RStudio) with `debug(fredr_series_observations)` and then rerun the code in question.

@DavisVaughan Perhaps related to the response timeout issues addressed in #70 ?

**Comment by DavisVaughan** [comment]
@sboysel probably, retrying like we do now might end up helping the finicky-ness

**Comment by ceschi** [comment]
@sboysel Same version I am using. The `/(.,1000)` part is just to divide everything by 1000 from millions to billions. Last time I tried it took like 12 tries before having the error again. It is exactly part of a bigger script that collects a number of series. I'll try with the debugger then, thanks!

**Comment by sboysel** [comment]
@ceschi You could also try installing the development version of `fredr` that as of #70 , will retry `GET` requests up to 10 times.  This can be done with `devtools::install_github('sboysel/fredr')`.
