### ISSUE TITLE
Removed from CRAN?

### ISSUE THREAD

**Issue by schoewed** [sboysel/fredr#76]
Hey! Just curious why this was recently pulled from the CRAN repo? I downloaded the devtools version  but was curious what happened. Let me know, seems like a great package!

**Comment by rcberg** [comment]
not updated for R 4.0.0 it seems :\

**Comment by sboysel** [comment]
@schoewed Unfortunately yes.  I'm taking a look at it tonight so hopefully I can resubmit and have it back on CRAN within a few days.  Duplicate of #75 so I'll redirect any concern to that issue.
