### ISSUE TITLE
Fredr can't return a legit series_id

### ISSUE THREAD

**Issue by DavideMagno** [sboysel/fredr#80]
Hi, first of all thanks a lot for the amazing package. 

I am trying to download the following ticker

![image](https://user-images.githubusercontent.com/9103832/94725163-3e75ab80-0353-11eb-829f-20a4676753e4.png)

but fredr returns me the following response:

```
> fredr::fredr(series_id = "USD3MTD156N")
Error in (function (endpoint, ..., to_frame = TRUE, print_req = FALSE)  : 
  404: Not Found.  The series does not exist.
```

How can I check the legitimacy of a series_id?

**Comment by DavideMagno** [comment]
Update: as "LIBOR Rates" category is 33003 i run the following:

```
> fredr::fredr_category_series(category_id = 33003L)
# A tibble: 0 x 0
```

is there any workaround?

**Comment by yanlesin** [comment]
What do you get for this?
```
series <- fredr_series_search_id(search_text = "LIBOR",
                       limit = 100)
```

**Comment by DavisVaughan** [comment]
I'm not sure why that series isn't available. It is not a fredr bug, as hitting the api directly in the browser shows the same thing. I've sent the people at FRED an email asking if they have any advice

**Comment by DavisVaughan** [comment]
This is what I got back

---

Hi,

 

The source of the following releases, ICE Libor Rates, ICE Swap Rates, LBMA Gold Price: Daily Prices, and LBMA Silver Price: Daily Prices, will not let us redistribute their data in our Excel Add-in and API. Previously, this data was available in all the FRED products, but the series will no longer be accessible through the above-mentioned products.

 

For the users reporting this issue, we recommend they download the data directly from the FRED website.

The releases and the series in them could be found starting here: https://fred.stlouisfed.org/source?soid=62

 

We apologize for the inconvenience.

 

Best,

FRED Team
