### ISSUE TITLE
way to traverse category trees?

### ISSUE THREAD

**Issue by thistleknot** [sboysel/fredr#85]
similar to traverseCategories found here?

https://github.com/jcizel/FredR/blob/master/R/FredR.R

I'm having a hard time exploring all the categories.  I have to sift through them manually and what I'd  like to do is start at a base node up top and sort all the way down by popularity but I need to be able to traverse the tree first.

**Comment by DavisVaughan** [comment]
That function isn't exported, so im not really sure what it actually does.

fredr is really designed for you to use it in conjunction with the FRED site. For example, they have a category section
https://fred.stlouisfed.org/categories/

Clicking on Money and Banking -> Exchange Rates -> Daily Rates, I can see all the daily rate series and can use their drop down to sort.

At the top in the URL, I can see the category id for Daily Rates is 94, which I can use in more fredr functions if I want.

You can incrementally get your way there with `fredr_category_children()`, but I still needed to reference the website to figure out the path to get to the Daily Series category.

```r
library(fredr)
#> Warning: package 'fredr' was built under R version 4.0.2

fredr_category_children(0)
#> # A tibble: 8 x 3
#>      id name                                    parent_id
#>   <int> <chr>                                       <int>
#> 1 32991 Money, Banking, & Finance                       0
#> 2    10 Population, Employment, & Labor Markets         0
#> 3 32992 National Accounts                               0
#> 4     1 Production & Business Activity                  0
#> 5 32455 Prices                                          0
#> 6 32263 International Data                              0
#> 7  3008 U.S. Regional Data                              0
#> 8 33060 Academic Data                                   0

fredr_category_children(32991)
#> # A tibble: 7 x 4
#>      id name               parent_id notes                                      
#>   <int> <chr>                  <int> <chr>                                      
#> 1    22 Interest Rates         32991  <NA>                                      
#> 2    15 Exchange Rates         32991  <NA>                                      
#> 3    24 Monetary Data          32991  <NA>                                      
#> 4    46 Financial Indicat…     32991  <NA>                                      
#> 5    23 Banking                32991  <NA>                                      
#> 6 32360 Business Lending       32991  <NA>                                      
#> 7 32145 Foreign Exchange …     32991 "In addition to the listed daily intervent…

fredr_category_children(15)
#> # A tibble: 5 x 4
#>      id name            parent_id notes                                         
#>   <int> <chr>               <int> <chr>                                         
#> 1    94 Daily Rates            15 "Effective January 1, 2009, the Federal Reser…
#> 2    95 Monthly Rates          15  <NA>                                         
#> 3 32219 Annual Rates           15  <NA>                                         
#> 4   105 Trade-Weighted…        15  <NA>                                         
#> 5   158 By Country             15  <NA>

fredr_category_series(94, order_by = "popularity")[c(1, 4, 5, 6)]
#> # A tibble: 35 x 4
#>    id       title                               observation_sta… observation_end
#>    <chr>    <chr>                               <chr>            <chr>          
#>  1 TWEXEME… Trade Weighted U.S. Dollar Index: … 2006-01-01       2019-01-01     
#>  2 TWEXAFE… Trade Weighted U.S. Dollar Index: … 2006-01-01       2019-01-01     
#>  3 TWEXBGS… Trade Weighted U.S. Dollar Index: … 2006-01-01       2019-01-01     
#>  4 DEXSLUS  Sri Lanka / U.S. Foreign Exchange … 1973-01-02       2020-11-25     
#>  5 TWEXEME… Trade Weighted U.S. Dollar Index: … 2006-01-01       2020-10-01     
#>  6 DTWEXO   Trade Weighted U.S. Dollar Index: … 1995-01-04       2019-12-31     
#>  7 DEXDNUS  Denmark / U.S. Foreign Exchange Ra… 1971-01-04       2020-11-25     
#>  8 TWEXAFE… Trade Weighted U.S. Dollar Index: … 2006-01-01       2020-10-01     
#>  9 DEXUSNZ  U.S. / New Zealand Foreign Exchang… 1971-01-04       2020-11-25     
#> 10 DEXVZUS  Venezuela / U.S. Foreign Exchange … 1995-01-02       2020-11-25     
#> # … with 25 more rows
```

I think it would be rather hard to show all recursive children of a node at once if that is what you are asking for

**Comment by thistleknot** [comment]
I figured out a way to do recursive functions

but it still returns empty tibbles, but I think I can clean that up on the backend
```
library(fredr)
fredr_set_key("getyourown")

recursive.categories <- function(x) {
  set <- fredr_category_children(category_id = x)
  print(set)
  if (length(set) == 0)    return (1)
  else  {
    
    #print(paste("waiting",floor(length(set)/2)+3))
    #Sys.sleep(floor(length(set)/2)+3)
    
    return (lapply(set[["id"]], function(y)
    {
    Sys.sleep(1)
    print(y)
    recursive.categories(y)
  }))}
}

cats <- recursive.categories(0)


```

**Comment by thistleknot** [comment]
fyi, the above code takes hours.  There's got to be an xml call that gives you all the nested categories

**Comment by thistleknot** [comment]
I tried data.tree but ended up writing my own function
`
data <- read.csv(file="combined.csv", header = TRUE)

print.matrix <- function(m){
  write.table(format(m, justify="right"),sep="\t",
              row.names=F, col.names=F, quote=F)
}

define.catt <- function(ntab = NULL){
  catt <- function(input = NULL){
    cat(paste0(paste(rep("\t", ntab), collapse = ""), input))
  }
  return(catt)
}

return.categories <- function(x, z=0) {
  
  catt <- define.catt(ntab = z)
  
  p <- data[which(data$id==x),]
  
  catt(print.matrix(cbind(p[,c(1,3,2)])))
  
  children <- data[which(data$parent_id==x),]
  
  if (nrow(children) == 0) {} else {
    z=z+1
    r <- lapply(data[which(data$parent_id==x),]$id, function(y)
    {
      return.categories(y,z)
    })
  }
}`

I'm not 100% sure how to work with recursive functions.  I can print just fine using them though.

![image](https://user-images.githubusercontent.com/5154106/100819794-81670480-3412-11eb-9c6e-e4f3131b01d9.png)

**Comment by thistleknot** [comment]
I got it!
I had to write.csv and cat them all into one file with id, name, parent_id, notes

but now this works

`
return.categories <- function(x) {
  
  p <- data[which(data$id==x),]
  
  #print(cbind(p[,c(1,3,2)]))
  
  children <- data[which(data$parent_id==x),]
  
  if (nrow(children) == 0) {return(p)} else {
    
    r <- lapply(data[which(data$parent_id==x),]$id, function(y)
    {
      
      return.categories(y)
    })
    #cat("\n")
    return(r)
  }
}

return.categories(32263)
`

**Comment by thistleknot** [comment]
![image](https://user-images.githubusercontent.com/5154106/100957974-0fa9bc00-34e1-11eb-9954-60416d05f166.png)

**Comment by thistleknot** [comment]
to have a version like that would require having the file pre downloaded ahead of time.  I intend on keeping a file I manually update yearly.

**Comment by thistleknot** [comment]
updated script 

library(fredr)
fredr_set_key("getyourown")

recursive.categories <- function(x) {
  
  #parent <- fredr_category(32998)
  parent <- fredr_category(x)
  
  children <- fredr_category_children(category_id = parent$id)
  
  print(parent)
  
  if (length(children) == 0)  {
    p <- cbind(parent$id,parent$name)
    names(p) <- paste(parent$id,parent$name)
    return (p)
  }
  
  else  {
    c <- (lapply(children[["id"]], function(y)
    {
      Sys.sleep(.5)
      print(y)
      recursive.categories(y)
    }))
  names(c) <- paste(children$id,children$name)
  return(c)
  }
  
}
sets <- recursive.categories(32998)
View(sets)

**Comment by DavisVaughan** [comment]
@thistleknot I'm happy to hear that you found a solution that works for you, however, I think that fredr should probably stick to just the API endpoints without too much additional work on top of it, so we probably won't add this. Thanks for detailing your solution though, in case anyone else needs this!
