### ISSUE TITLE
This likely isn't an issue with your code, but something to be wary of

### ISSUE THREAD

**Issue by thistleknot** [sboysel/fredr#86]
I had some categories I had picked out manually from some lists that FRED had published and I was comparing them against what I downloaded and noticed they weren't in any of the lists that fredr downloads.  So i looked into the api calls and it looks like the API stops at 1000 returns

for example

fredr_series_categories("UMCSENT")
is part of 32457 but you won't see if when you do a

fredr_category_series(32457)$id

so far I've checked some others and it appears when implementing the calls they stop at 1000

I don't know how to solve this nor where to go to get all the entries per series.  Another series that has a similar problem is 97 (housing)

**Comment by thistleknot** [comment]
I see there is a limit and pagination... ugh... going to have the joy of figuring out which series have more than 1000 entries

**Comment by sboysel** [comment]
The `limit` parameter is documented for some endpoints (e.g. `fred/seriesobservations`) and is not documented.  My hunch is there is an implicit 1000 limit for `fred/series/categories`.  In any case, pagination solutions are something we discuss in #68 .

**Comment by thistleknot** [comment]
Thanks. I ended up retrofitting my code to check the nrow's returned and do a do-while loop (thank you business programming lbcc)  But I'm glad you are aware of it.  You did add the offset paramater so I was able to make due.  This can be closed.  Albeit I'm sure people will want the solution.
