### ISSUE TITLE
fredr appears to be completely broken on my R setup

### ISSUE THREAD

**Issue by binkleym** [sboysel/fredr#96]
I have the Ubuntu Focal default R (3.6.3) installed on my server, with RStudio Server running.    I am running fredr 2.1.0.

Running the following minimal R script:

library(fredr)
fredr_set_key(api_key_fred)
foo <- fredr(series_id = "SP500")

Yields the following error:

> foo <- fredr(series_id = "SP500")
Error: : 
  Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/rlang_error>
  : 
  Backtrace:
  1. fredr::fredr(series_id = "SP500")
Run `rlang::last_trace()` to see the full context.
> rlang::last_trace()
<error/rlang_error>
  : 
  Backtrace:
  █
1. └─fredr::fredr(series_id = "SP500")
2.   ├─base::do.call(fredr_request, c(fredr_args, user_args))
3.   └─(function (endpoint, ..., to_frame = TRUE, print_req = FALSE, ...

Let me know if there's any other info I can give you.

**Comment by mgordonRa** [comment]
This exact issue has just arisen for me too, this morning. I was right about to post an issue myself.

For context, I was able to use fredr last Friday. This morning I booted up a project file using fredr and received an error. I then tried changing my api to see if that was an issue to no avail. I received the same error.

> rlang::last_error()
<error/rlang_error>
: 
Backtrace:
 1. fredr::fredr(...)
Run `rlang::last_trace()` to see the full context.

> rlang::last_trace
function () 
{
    err <- last_error()
    err$rlang$internal$print_simplify <- "none"
    err
}
<bytecode: 0x000001b627a3bfd8>
<environment: namespace:rlang>

**Comment by DavisVaughan** [comment]
I think the FRED API is just down. Pasting the following into my browser with `<MY_KEY>` replaced with my actual key gives me a 500 internal server error

```r
https://api.stlouisfed.org/fred/series/observations?series_id=GNPCA&api_key=<MY_KEY>
```

**Comment by SamuelLeeD** [comment]
I'm having this problem at the moment, and I think it's just that the FRED API is down at the moment.

Using FRED's API link to request a series returns an Internal Server Error: https://api.stlouisfed.org/fred/series?series_id=GNPCA&api_key=abcdefghijklmnopqrstuvwxyz123456

Edit: Right as I was typing this, it seems to work now.

However, it does seem that the error handling in `fredr` is faulty at the moment, and doesn't correctly output the error code and error message, which is why you got a blank error message.

**Comment by DavisVaughan** [comment]
It does seem to be back now

**Comment by mgordonRa** [comment]
It's working again!

**Comment by sboysel** [comment]
@DavisVaughan maybe we can implement an early and informative check to see if the API is down?
